### ISSUE TITLE
New Feature: add Index to PropertyChange

### ISSUE THREAD

**Issue by StefanLindel** [fujaba/NetworkParser#10]
SimpleSet mit Index in PropertyChange

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)
* Issue title must be in imperative, present tense \(e\.g\. "add", "fix", "change"\) [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/fujaba/NetworkParser/10/9e5c3be8-75de-4091-9e56-6f667935e56a/7890b2ef-12d9-4075-8df1-d6941e381141) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
This issue still violates some of our guidelines:

* Issue title must be in imperative, present tense \(e\.g\. "add", "fix", "change"\) [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/fujaba/NetworkParser/10/9e5c3be8-75de-4091-9e56-6f667935e56a/7890b2ef-12d9-4075-8df1-d6941e381141) for details.

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:

**Comment by StefanLindel** [comment]
close
