### ISSUE TITLE
New Feature: add Switch for Referenzobjekt to Serialization

### ISSUE THREAD

**Issue by StefanLindel** [fujaba/NetworkParser#11]
add a switch for do not create Referenceobjects

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue title must start with uppercase [(?)](https://gitmagic.io/rules/#/issue/subject-must-start-with-case)

[Click here](https://app.gitmagic.io/fujaba/NetworkParser/11/9e5c3be8-75de-4091-9e56-6f667935e56a/3a95340c-3608-4d46-b851-a1d32ab64cd5) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:

**Comment by StefanLindel** [comment]
finsih work
