### ISSUE TITLE
ConcurrentModificationException on remove you

### ISSUE THREAD

**Issue by BiggA94** [fujaba/NetworkParser#8]
To reproduce:
The following generates a Concurrent Modification Exception:
```
@Test
public void testRemoveObj(){
   University uni = new University().withName("UniKasselVersitaet");
   Student student1 = uni.createStudents().withName("Peter");
   Student student2 = uni.createStudents().withName("Paul");
   Student student3 = uni.createStudents().withName("Mary");

   IdMap idMap = UniversityCreator.createIdMap("u");
   idMap.toJsonArray(uni);
   uni.removeYou();
}
```

One solution for this problem is to remove 

```
Collection<?> continee = (Collection<?>) reference;
Iterator<?> i = continee.iterator();
while (i.hasNext()) {
   creator.setValue(oldValue, prop, i.next(),
   SendableEntityCreator.REMOVE);
}

```

and replace it with

```
Object[] array = ((Collection) reference).toArray();
for (int i = 0; i < array.length; i++) {
   Object object = array[i];
   creator.setValue(oldValue, prop, object,
   SendableEntityCreator.REMOVE);
}

```
(IdMap, line 422ff)
This works for newly generated Models but not for the one, that is inside the test-package.
And it is also slower.

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)

[Click here](https://app.gitmagic.io/fujaba/NetworkParser/8/9e5c3be8-75de-4091-9e56-6f667935e56a/20d284ab-f8a1-4888-a54d-4d1f8e045caf) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
This issue still violates some of our guidelines:

* Issue description must include reproduction steps [(?)](https://gitmagic.io/rules/#/issue/body-must-include-reproduction-steps)

[Click here](https://app.gitmagic.io/fujaba/NetworkParser/8/9e5c3be8-75de-4091-9e56-6f667935e56a/20d284ab-f8a1-4888-a54d-4d1f8e045caf) for details.

**Comment by ghost** [comment]
This issue still violates some of our guidelines:

* Issue description must include reproduction steps [(?)](https://gitmagic.io/rules/#/issue/body-must-include-reproduction-steps)

[Click here](https://app.gitmagic.io/fujaba/NetworkParser/8/9e5c3be8-75de-4091-9e56-6f667935e56a/20d284ab-f8a1-4888-a54d-4d1f8e045caf) for details.

**Comment by ghost** [comment]
This issue still violates some of our guidelines:

* Issue description must include reproduction steps [(?)](https://gitmagic.io/rules/#/issue/body-must-include-reproduction-steps)

[Click here](https://app.gitmagic.io/fujaba/NetworkParser/8/9e5c3be8-75de-4091-9e56-6f667935e56a/20d284ab-f8a1-4888-a54d-4d1f8e045caf) for details.

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:

**Comment by StefanLindel** [comment]
Use a SimpleIterator for moving over a Collection
