### ISSUE TITLE
New Feature: Add TimeStamp to UpdateMessages

### ISSUE THREAD

**Issue by StefanLindel** [fujaba/NetworkParser#9]
TimeStamp in UpdateJson integrieren

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)
* Issue title must be in imperative, present tense \(e\.g\. "add", "fix", "change"\) [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/fujaba/NetworkParser/9/9e5c3be8-75de-4091-9e56-6f667935e56a/f35c54a5-f6fa-40c3-8c22-be9ea733a414) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
This issue still violates some of our guidelines:

* Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)

[Click here](https://app.gitmagic.io/fujaba/NetworkParser/9/9e5c3be8-75de-4091-9e56-6f667935e56a/f35c54a5-f6fa-40c3-8c22-be9ea733a414) for details.

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:
